---
version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24  

services:
  sbt:
    container_name: sbt
    image: mozilla/sbt:8u212_1.2.8 
    networks:
      - arc-integration     
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app  
      - /tmp/pgp:/pgp
    working_dir: /app

  minio:
    image: minio/minio:it
    build: minio/.
    networks:
      - arc-integration    
    ports:
      - 9000:9000      
    command: server /it
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  mc:
    image: minio/mc:it
    build: mc/.
    networks:
      - arc-integration
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 